/**
 * Compliance report: names, rule ids, disclaimer, toggles — all measured against
 * the explicit review fixture in helpers.ts, never against a review node's own
 * output, since the review nodes live in plugins/aec-review (ADR-0008).
 */
import { describe, expect, it } from 'vitest';
import { runNode } from '@archspace/node-sdk/testkit';
import { generateComplianceReportNode, projectBriefNode } from '../src/index.js';
import { toValue } from '../src/util.js';
import { reviewFixture, runPipeline } from './helpers.js';

const DISCLAIMER = 'Generated by Archspace mock review pipeline — not a code compliance determination.';

describe('aec.generate_compliance_report', () => {
  it('contains the project name, every violated rule id, and the disclaimer', async () => {
    const run = await runPipeline();
    const report = run.report.outputs.report as string;
    const review = run.review;

    expect(report).toContain('Riverside Office Tower');
    expect(report).toContain(DISCLAIMER);

    const violatedRuleIds = new Set(
      review.findings.filter((f) => f.severity === 'violation').map((f) => f.ruleId),
    );
    expect(violatedRuleIds.size).toBeGreaterThan(0);
    for (const ruleId of violatedRuleIds) expect(report).toContain(ruleId);
  });

  it('include_passed_summary toggles the passed-checks section', async () => {
    const withSection = await runPipeline();
    const withoutSection = await runPipeline({ report: { include_passed_summary: false } });
    expect(withSection.report.outputs.report as string).toContain('## Passed checks');
    expect(withoutSection.report.outputs.report as string).not.toContain('## Passed checks');
  });

  it('reports the passed/checked split the review claims', async () => {
    // The fixture's split is stated, so the numbers the node prints are
    // checkable — with a live review node upstream they were whatever it emitted.
    const run = await runPipeline();
    const { passed, checked } = run.review.summary;
    expect(passed).toBeLessThan(checked);
    expect(run.report.outputs.report as string).toContain(`${passed} of ${checked} checks passed`);
  });

  it('tone switches phrasing without changing the facts', async () => {
    const formal = await runPipeline();
    const brief = await runPipeline({ report: { tone: 'brief' } });
    const formalText = formal.report.outputs.report as string;
    const briefText = brief.report.outputs.report as string;
    expect(formalText).not.toBe(briefText);
    expect(briefText).toContain('Riverside Office Tower');
    expect(briefText).toContain(DISCLAIMER);
    expect(formalText.length).toBeGreaterThan(briefText.length);
  });

  it('reports on a review that carries no code block, such as a merged one', async () => {
    // The shipped branching-review example wires aec.review.merge_findings
    // straight into this node, and a merged review is a plain ReviewResult —
    // only the code-discipline review has `code`. Reading `code.version`
    // unconditionally killed that workflow with "Cannot read properties of
    // undefined (reading 'version')", and nothing caught it because CI ran
    // only one of the three shipped examples.
    const merged = reviewFixture();
    delete (merged as { code?: unknown }).code;
    merged.standard = { name: 'multi-discipline', version: '3 reviews' };

    const brief = await runNode(projectBriefNode, {});
    const run = await runNode(generateComplianceReportNode, {
      params: { mock_latency_ms: 0 },
      inputs: { brief: brief.outputs.brief, review: toValue(merged) },
    });

    const report = run.outputs.report as string;
    expect(report).toContain('multi-discipline 3 reviews');
    expect(report).not.toContain('undefined');
  });
});
