/** Compliance report: names, rule ids, disclaimer, toggles. */
import { describe, expect, it } from 'vitest';
import type { ComplianceReviewResult } from '../src/index.js';
import { runPipeline } from './helpers.js';

const DISCLAIMER = 'Generated by Archspace mock review pipeline — not a code compliance determination.';

describe('aec.generate_compliance_report', () => {
  it('contains the project name, every violated rule id, and the disclaimer', async () => {
    const run = await runPipeline({ plan: { door_width_mm: 800 } });
    const report = run.report.outputs.report as string;
    const review = run.review.outputs.result as unknown as ComplianceReviewResult;

    expect(report).toContain('Riverside Office Tower');
    expect(report).toContain(DISCLAIMER);

    const violatedRuleIds = new Set(
      review.findings.filter((f) => f.severity === 'violation').map((f) => f.ruleId),
    );
    expect(violatedRuleIds.size).toBeGreaterThan(0);
    for (const ruleId of violatedRuleIds) expect(report).toContain(ruleId);
  });

  it('include_passed_summary toggles the passed-checks section', async () => {
    const withSection = await runPipeline();
    const withoutSection = await runPipeline({ report: { include_passed_summary: false } });
    expect(withSection.report.outputs.report as string).toContain('## Passed checks');
    expect(withoutSection.report.outputs.report as string).not.toContain('## Passed checks');
  });

  it('tone switches phrasing without changing the facts', async () => {
    const formal = await runPipeline();
    const brief = await runPipeline({ report: { tone: 'brief' } });
    const formalText = formal.report.outputs.report as string;
    const briefText = brief.report.outputs.report as string;
    expect(formalText).not.toBe(briefText);
    expect(briefText).toContain('Riverside Office Tower');
    expect(briefText).toContain(DISCLAIMER);
    expect(formalText.length).toBeGreaterThan(briefText.length);
  });
});
