/**
 * aec.generate_compliance_report — MOCK of an AI report writer.
 * Deterministic markdown: no model call, no randomness; `tone` switches
 * between longer and shorter phrasing. A real AI backend would substitute
 * inside execute() and still return a markdown `text` report.
 */
import type { NodeModule } from '@archspace/node-sdk';
import type { ComplianceFinding, ComplianceReviewResult, ProjectBrief } from './shapes.js';
import { requireInput, sleep } from './util.js';

export interface GenerateComplianceReportParams {
  include_passed_summary: boolean;
  tone: 'formal' | 'brief';
  mock_latency_ms: number;
}

const DISCLAIMER = 'Generated by Archspace mock review pipeline — not a code compliance determination.';

const SEVERITY_ORDER: { severity: ComplianceFinding['severity']; heading: string }[] = [
  { severity: 'violation', heading: 'Violations' },
  { severity: 'warning', heading: 'Warnings' },
  { severity: 'advisory', heading: 'Advisories' },
];

export const generateComplianceReportNode: NodeModule<GenerateComplianceReportParams> = {
  manifest: {
    type: 'aec.generate_compliance_report',
    version: 1,
    label: 'Generate Compliance Report',
    description:
      'Mock AI report writer: drafts a deterministic markdown compliance report from the brief and the review result.',
    category: 'Report',
    keywords: ['report', 'compliance', 'markdown', 'mock'],
    caching: 'never',
    lane: 'ai',
    params: {
      type: 'object',
      properties: {
        include_passed_summary: {
          type: 'boolean',
          title: 'Include passed-checks summary',
          default: true,
        },
        tone: {
          type: 'string',
          title: 'Tone',
          enum: ['formal', 'brief'],
          default: 'formal',
        },
        mock_latency_ms: {
          type: 'integer',
          title: 'Mock latency (ms)',
          default: 900,
          minimum: 0,
        },
      },
    },
    inputs: [
      { id: 'brief', type: 'json', label: 'Brief', required: true },
      { id: 'review', type: 'json', label: 'Review', required: true },
    ],
    outputs: [{ id: 'report', type: 'text', label: 'Report' }],
  },

  async execute(ctx, inputs, params) {
    const brief = requireInput<ProjectBrief>(inputs, 'brief', 'aec.generate_compliance_report');
    const review = requireInput<ComplianceReviewResult>(inputs, 'review', 'aec.generate_compliance_report');

    ctx.progress(0.3, 'drafting report');
    await sleep(params.mock_latency_ms / 2, ctx.signal);

    const { checked, passed, advisories, warnings, violations } = review.summary;
    const formal = params.tone === 'formal';
    const lines: string[] = [];

    lines.push(`# Code Compliance Report — ${brief.projectName}`, '');

    lines.push(
      '| Item | Value |',
      '| --- | --- |',
      `| Building type | ${brief.buildingType} |`,
      `| Floors | ${brief.floors} |`,
      `| Site | ${brief.site.widthM} × ${brief.site.depthM} m (${brief.site.areaM2} m²) |`,
      `| Target gross area | ${brief.targetGrossAreaM2} m² |`,
      `| Occupancy class | ${brief.occupancyClass} |`,
      `| Code version | ${review.code.version} |`,
      '',
    );

    lines.push('## Executive summary', '');
    if (formal) {
      lines.push(
        violations > 0
          ? `This concept design review recorded ${violations} violation(s), ${warnings} warning(s), and ` +
              `${advisories} advisory note(s) across ${checked} automated checks against ${review.code.version}. ` +
              `The scheme requires design revisions before it can be considered code-conforming.`
          : `This concept design review completed ${checked} automated checks against ${review.code.version} ` +
              `with no violations (${warnings} warning(s), ${advisories} advisory note(s)). ` +
              `The scheme appears code-conforming at concept level.`,
      );
    } else {
      lines.push(
        `${violations} violations, ${warnings} warnings, ${advisories} advisories across ${checked} checks (${review.code.version}).`,
      );
    }
    lines.push('');

    for (const { severity, heading } of SEVERITY_ORDER) {
      const findings = review.findings.filter((f) => f.severity === severity);
      if (findings.length === 0) continue;
      lines.push(`## ${heading} (${findings.length})`, '');
      for (const f of findings) {
        const where = f.level === null ? '' : ` (level ${f.level})`;
        lines.push(`- **${f.ruleId} — ${f.title}**${where}: ${f.message}`);
      }
      lines.push('');
    }

    if (params.include_passed_summary) {
      lines.push('## Passed checks', '');
      lines.push(
        formal
          ? `${passed} of ${checked} checks passed, including minimum room areas, corridor widths, egress ` +
              `counts, and exit-access travel distances wherever no finding is listed above.`
          : `${passed}/${checked} checks passed.`,
      );
      lines.push('');
    }

    lines.push('---', '', DISCLAIMER, '');

    ctx.progress(0.9, 'formatting report');
    await sleep(params.mock_latency_ms / 2, ctx.signal);
    ctx.progress(1, 'report complete');

    return { report: lines.join('\n') };
  },
};
