/**
 * aec.compare_reviews — what a re-review actually changed.
 *
 * Pure and instant (no mock latency): a set difference over two ReviewResults.
 * Findings are matched across the two runs by IDENTITY — ruleId + level +
 * sorted elementIds — never by finding id, because ids ("f_001"…) are assigned
 * per review run and would make every re-review look like a total rewrite.
 * The ReviewComparisonResult shape (shapes.ts) is the contract.
 */
import type { NodeModule, Value } from '@archspace/node-sdk';
import type {
  ComparisonVerdict,
  FindingSeverity,
  ReviewComparisonResult,
  ReviewFinding,
  ReviewResult,
  TableValue,
} from './shapes.js';
import { fnv1a, hex8, mulberry32, requireInput, toValue } from './util.js';

export interface CompareReviewsParams {
  tone: 'formal' | 'brief';
  include_persisting: boolean;
}

/** Same disclaimer line the compliance report closes with. */
const DISCLAIMER = 'Generated by Archspace mock review pipeline — not a code compliance determination.';

/**
 * Stable identity of a finding across review runs. Element ids are sorted so
 * that a reviewer listing the same two doors in a different order still
 * matches; the finding's own id is deliberately not part of the key.
 */
function identity(f: ReviewFinding): string {
  return `${f.ruleId}|${f.level}|${[...f.elementIds].sort().join(',')}`;
}

interface SeverityCounts {
  violations: number;
  warnings: number;
  advisories: number;
}

/** Count severities from the findings themselves — the ground truth a summary
 *  merely echoes, so the delta always agrees with the partitions below. */
function countSeverities(findings: readonly ReviewFinding[]): SeverityCounts {
  const of = (s: FindingSeverity): number => findings.filter((f) => f.severity === s).length;
  return { violations: of('violation'), warnings: of('warning'), advisories: of('advisory') };
}

/**
 * Verdict precedence, in this order (first match wins):
 *   1. `unchanged`  — nothing resolved and nothing introduced; the two reviews
 *                     describe the same set of findings.
 *   2. `regressed`  — violations went up, OR the only movement is introductions
 *                     (nothing was resolved at all).
 *   3. `improved`   — violations went down and nothing new appeared.
 *   4. `mixed`      — everything else: movement in both directions, or movement
 *                     that leaves the violation count where it was.
 * Regressed is tested before improved so that a change which both raises the
 * violation count and resolves something is never reported as an improvement.
 */
function verdictOf(
  resolved: readonly ReviewFinding[],
  introduced: readonly ReviewFinding[],
  deltaViolations: number,
): ComparisonVerdict {
  if (resolved.length === 0 && introduced.length === 0) return 'unchanged';
  if (deltaViolations > 0 || resolved.length === 0) return 'regressed';
  if (deltaViolations < 0 && introduced.length === 0) return 'improved';
  return 'mixed';
}

/** "+2" / "-8" / "0" — a delta always reads as a delta. */
function signed(n: number): string {
  return n > 0 ? `+${n}` : String(n);
}

export const compareReviewsNode: NodeModule<CompareReviewsParams> = {
  manifest: {
    type: 'aec.compare_reviews',
    version: 1,
    label: 'Compare Reviews',
    description:
      'What a re-review actually changed — findings resolved, findings introduced, and the verdict.',
    category: 'Report',
    keywords: ['compare', 'diff', 'review', 'regression', 'verdict'],
    caching: 'pure',
    lane: 'cpu',
    params: {
      type: 'object',
      properties: {
        tone: {
          type: 'string',
          title: 'Tone',
          enum: ['formal', 'brief'],
          default: 'formal',
        },
        include_persisting: {
          type: 'boolean',
          title: 'Include persisting findings',
          description: 'List findings present in both reviews in the delta table and the report.',
          default: true,
        },
      },
    },
    inputs: [
      { id: 'before', type: 'json', label: 'Before', required: true },
      { id: 'after', type: 'json', label: 'After', required: true },
    ],
    outputs: [
      { id: 'comparison', type: 'json', label: 'Comparison' },
      { id: 'delta', type: 'table', label: 'Delta' },
      { id: 'report', type: 'text', label: 'Report' },
    ],
  },

  async execute(ctx, inputs, params) {
    const before = requireInput<ReviewResult>(inputs, 'before', 'aec.compare_reviews');
    const after = requireInput<ReviewResult>(inputs, 'after', 'aec.compare_reviews');

    if (before.discipline !== after.discipline) {
      ctx.log(
        'warn',
        `comparing a ${before.discipline} review with a ${after.discipline} review — findings from different rule sets rarely match`,
      );
    }

    const beforeKeys = new Set(before.findings.map(identity));
    const afterKeys = new Set(after.findings.map(identity));

    // Source order is preserved inside each partition, so the output is stable.
    const resolved = before.findings.filter((f) => !afterKeys.has(identity(f)));
    const introduced = after.findings.filter((f) => !beforeKeys.has(identity(f)));
    // Persisting carries the AFTER copy: same finding, current ids and wording.
    const persisting = after.findings.filter((f) => beforeKeys.has(identity(f)));

    const beforeCounts = countSeverities(before.findings);
    const afterCounts = countSeverities(after.findings);
    const delta = {
      violations: afterCounts.violations - beforeCounts.violations,
      warnings: afterCounts.warnings - beforeCounts.warnings,
      advisories: afterCounts.advisories - beforeCounts.advisories,
    };

    const comparison: ReviewComparisonResult = {
      comparisonId: `cmp_${hex8(mulberry32(fnv1a(`${before.reviewId}->${after.reviewId}`)))}`,
      before: { reviewId: before.reviewId, discipline: before.discipline, summary: before.summary },
      after: { reviewId: after.reviewId, discipline: after.discipline, summary: after.summary },
      resolved,
      introduced,
      persisting,
      delta,
      verdict: verdictOf(resolved, introduced, delta.violations),
    };

    // ---- delta table -------------------------------------------------------
    const deltaRow = (change: string, f: ReviewFinding): Record<string, Value> => ({
      change,
      rule_id: f.ruleId,
      severity: f.severity,
      level: f.level,
      elements: f.elementIds.join(', '),
      message: f.message,
    });
    const deltaTable: TableValue = {
      columns: [
        { id: 'change', label: 'Change' },
        { id: 'rule_id', label: 'Rule' },
        { id: 'severity', label: 'Severity' },
        { id: 'level', label: 'Level' },
        { id: 'elements', label: 'Elements' },
        { id: 'message', label: 'Message' },
      ],
      rows: [
        ...resolved.map((f) => deltaRow('resolved', f)),
        ...introduced.map((f) => deltaRow('introduced', f)),
        ...(params.include_persisting ? persisting.map((f) => deltaRow('persisting', f)) : []),
      ],
    };

    // ---- markdown report ---------------------------------------------------
    const formal = params.tone === 'formal';
    const beforeTotal = before.findings.length;
    const afterTotal = after.findings.length;
    const lines: string[] = [];

    const heading =
      before.discipline === after.discipline
        ? `${before.discipline} review`
        : `${before.discipline} → ${after.discipline}`;
    lines.push(`# Review Comparison — ${heading}`, '');

    if (formal) {
      lines.push(`Comparing \`${before.reviewId}\` (before) with \`${after.reviewId}\` (after).`, '');
    }

    lines.push('## Verdict', '');
    if (formal) {
      switch (comparison.verdict) {
        case 'unchanged':
          lines.push(
            `The re-review reports the same ${afterTotal} finding(s) as the original: nothing was ` +
              `resolved and nothing was introduced.`,
          );
          break;
        case 'improved':
          lines.push(
            `The re-review resolved ${resolved.length} finding(s) and introduced none; violations fell ` +
              `from ${beforeCounts.violations} to ${afterCounts.violations}.`,
          );
          break;
        case 'regressed':
          lines.push(
            `The re-review introduced ${introduced.length} finding(s) against ${resolved.length} resolved; ` +
              `violations moved from ${beforeCounts.violations} to ${afterCounts.violations}.`,
          );
          break;
        case 'mixed':
          lines.push(
            `The re-review resolved ${resolved.length} finding(s) but introduced ${introduced.length}; ` +
              `violations moved from ${beforeCounts.violations} to ${afterCounts.violations}.`,
          );
          break;
      }
    } else {
      lines.push(
        `${comparison.verdict} — ${resolved.length} resolved, ${introduced.length} introduced, ` +
          `${persisting.length} persisting; violations ${beforeCounts.violations} → ${afterCounts.violations}.`,
      );
    }
    lines.push('');

    lines.push(
      '| Severity | Before | After | Delta |',
      '| --- | --- | --- | --- |',
      `| Violations | ${beforeCounts.violations} | ${afterCounts.violations} | ${signed(delta.violations)} |`,
      `| Warnings | ${beforeCounts.warnings} | ${afterCounts.warnings} | ${signed(delta.warnings)} |`,
      `| Advisories | ${beforeCounts.advisories} | ${afterCounts.advisories} | ${signed(delta.advisories)} |`,
      `| Total | ${beforeTotal} | ${afterTotal} | ${signed(afterTotal - beforeTotal)} |`,
      '',
    );

    // `brief` drops the persisting section outright; `include_persisting`
    // governs it in both tones (and governs the delta table independently).
    const sections: { heading: string; findings: ReviewFinding[] }[] = [
      { heading: 'Resolved', findings: resolved },
      { heading: 'Introduced', findings: introduced },
      ...(params.include_persisting && formal ? [{ heading: 'Persisting', findings: persisting }] : []),
    ];
    for (const section of sections) {
      if (section.findings.length === 0) continue;
      lines.push(`## ${section.heading} (${section.findings.length})`, '');
      for (const f of section.findings) {
        const where = f.level === null ? '' : ` (level ${f.level})`;
        lines.push(`- **${f.ruleId} — ${f.title}**${where}: ${f.message}`);
      }
      lines.push('');
    }

    lines.push('---', '', DISCLAIMER, '');

    return {
      comparison: toValue(comparison),
      delta: toValue(deltaTable),
      report: lines.join('\n'),
    };
  },
};
