/**
 * aec.generate_compliance_report — MOCK of an AI report writer.
 * Deterministic markdown: no model call, no randomness; `tone` switches
 * between longer and shorter phrasing. A real AI backend would substitute
 * inside execute() and still return a markdown `text` report.
 */
import type { NodeModule } from '@archspace/node-sdk';
import type { ComplianceFinding, ComplianceReviewResult, ProjectBrief, ReviewResult } from './shapes.js';
import { requireInput, sleep } from './util.js';

export interface GenerateComplianceReportParams {
  include_passed_summary: boolean;
  tone: 'formal' | 'brief';
  mock_latency_ms: number;
}

const DISCLAIMER = 'Generated by Archspace mock review pipeline — not a code compliance determination.';

const SEVERITY_ORDER: { severity: ComplianceFinding['severity']; heading: string }[] = [
  { severity: 'violation', heading: 'Violations' },
  { severity: 'warning', heading: 'Warnings' },
  { severity: 'advisory', heading: 'Advisories' },
];

/**
 * What the report names as the rule set it was checked against.
 *
 * The code review phrases its own version ("IBC 2024") in `code.version`, so
 * that wins when it is there. Every other review — accessibility, zoning,
 * energy, and anything merged — carries only `standard`, which is the field
 * `ReviewResult` guarantees. Reading `code` unconditionally was a bug that only
 * showed up when a review other than the code one reached this node.
 */
function standardLabel(review: ReviewResult): string {
  const code = (review as Partial<ComplianceReviewResult>).code;
  if (typeof code?.version === 'string' && code.version !== '') return code.version;
  const { name, version } = review.standard;
  return version === '' ? name : `${name} ${version}`;
}

export const generateComplianceReportNode: NodeModule<GenerateComplianceReportParams> = {
  manifest: {
    type: 'aec.generate_compliance_report',
    version: 1,
    label: 'Generate Compliance Report',
    description:
      'Mock AI report writer: drafts a deterministic markdown compliance report from the brief and the review result.',
    category: 'Report',
    keywords: ['report', 'compliance', 'markdown', 'mock'],
    caching: 'never',
    lane: 'ai',
    params: {
      type: 'object',
      properties: {
        include_passed_summary: {
          type: 'boolean',
          title: 'Include passed-checks summary',
          default: true,
        },
        tone: {
          type: 'string',
          title: 'Tone',
          enum: ['formal', 'brief'],
          default: 'formal',
        },
        mock_latency_ms: {
          type: 'integer',
          title: 'Mock latency (ms)',
          default: 900,
          minimum: 0,
        },
      },
    },
    inputs: [
      { id: 'brief', type: 'json', label: 'Brief', required: true },
      { id: 'review', type: 'json', label: 'Review', required: true },
    ],
    outputs: [{ id: 'report', type: 'text', label: 'Report' }],
  },

  async execute(ctx, inputs, params) {
    const brief = requireInput<ProjectBrief>(inputs, 'brief', 'aec.generate_compliance_report');
    // `ReviewResult`, not `ComplianceReviewResult`: the port is `json` and any
    // review can be wired into it — an accessibility one, an energy one, or the
    // output of `aec.review.merge_findings`, which is the shipped
    // branching-review example's whole shape. Only the code-discipline review
    // carries `code`, so typing it as present here is what made that example
    // die with "Cannot read properties of undefined (reading 'version')".
    const review = requireInput<ReviewResult>(inputs, 'review', 'aec.generate_compliance_report');
    const standard = standardLabel(review);

    ctx.progress(0.3, 'drafting report');
    await sleep(params.mock_latency_ms / 2, ctx.signal);

    const { checked, passed, advisories, warnings, violations } = review.summary;
    const formal = params.tone === 'formal';
    const lines: string[] = [];

    lines.push(`# Code Compliance Report — ${brief.projectName}`, '');

    lines.push(
      '| Item | Value |',
      '| --- | --- |',
      `| Building type | ${brief.buildingType} |`,
      `| Floors | ${brief.floors} |`,
      `| Site | ${brief.site.widthM} × ${brief.site.depthM} m (${brief.site.areaM2} m²) |`,
      `| Target gross area | ${brief.targetGrossAreaM2} m² |`,
      `| Occupancy class | ${brief.occupancyClass} |`,
      `| Checked against | ${standard} |`,
      '',
    );

    lines.push('## Executive summary', '');
    if (formal) {
      lines.push(
        violations > 0
          ? `This concept design review recorded ${violations} violation(s), ${warnings} warning(s), and ` +
              `${advisories} advisory note(s) across ${checked} automated checks against ${standard}. ` +
              `The scheme requires design revisions before it can be considered code-conforming.`
          : `This concept design review completed ${checked} automated checks against ${standard} ` +
              `with no violations (${warnings} warning(s), ${advisories} advisory note(s)). ` +
              `The scheme appears code-conforming at concept level.`,
      );
    } else {
      lines.push(
        `${violations} violations, ${warnings} warnings, ${advisories} advisories across ${checked} checks (${standard}).`,
      );
    }
    lines.push('');

    for (const { severity, heading } of SEVERITY_ORDER) {
      const findings = review.findings.filter((f) => f.severity === severity);
      if (findings.length === 0) continue;
      lines.push(`## ${heading} (${findings.length})`, '');
      for (const f of findings) {
        const where = f.level === null ? '' : ` (level ${f.level})`;
        lines.push(`- **${f.ruleId} — ${f.title}**${where}: ${f.message}`);
      }
      lines.push('');
    }

    if (params.include_passed_summary) {
      lines.push('## Passed checks', '');
      lines.push(
        formal
          ? `${passed} of ${checked} checks passed, including minimum room areas, corridor widths, egress ` +
              `counts, and exit-access travel distances wherever no finding is listed above.`
          : `${passed}/${checked} checks passed.`,
      );
      lines.push('');
    }

    lines.push('---', '', DISCLAIMER, '');

    ctx.progress(0.9, 'formatting report');
    await sleep(params.mock_latency_ms / 2, ctx.signal);
    ctx.progress(1, 'report complete');

    return { report: lines.join('\n') };
  },
};
